// React/01_React+NodeJS/myapp_react/src/pages/Login/Login.jsx
import { useState } from "react";
import { useDispatch } from "react-redux";
import { loginUser } from "../../store/slices/authSlice";
import { useNavigate } from "react-router-dom";

function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const dispatch = useDispatch();
  const navigate = useNavigate();

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      await dispatch(loginUser({ email, password })).unwrap();
      navigate("/users"); // 登录成功跳转
    } catch (err) {
      alert("登录失败: " + err.message);
    }
  };

  return (
    <div className="login-page">
      <h2>登录</h2>
      <form onSubmit={handleLogin}>
        <input
          type="email"
          placeholder="邮箱"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        <input
          type="password"
          placeholder="密码"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <button type="submit">登录</button>
      </form>
    </div>
  );
}

export default Login;

// Vue/Vue + Nodejs + SSMS 01/myapp_v_vue/src/pages/Login.vue
<template>
  <div>
    <h2>Login</h2>
    <form @submit.prevent="login">
      <input v-model="email" placeholder="Email" />
      <input v-model="password" type="password" placeholder="Password" />
      <button>Login</button>
    </form>
    <p>{{ message }}</p>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import api from '../api/api'
import { useUserStore } from '../store/user'

const email = ref('')
const password = ref('')
const message = ref('')
const router = useRouter()
const userStore = useUserStore()

async function login() {
  try {
    const res = await api.post('/auth/login', {
      email: email.value,
      password: password.value
    })
    userStore.setUser(res.data.token, { email: email.value })
    message.value = 'Login successful!'
    router.push('/posts')
  } catch (err) {
    message.value = err.response?.data?.message || 'Error'
  }
}
</script>
